apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-git
spec:
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
              repoURL: https://github.com/codefresh-contrib/gitops-cert-level-2-examples.git
              revision: HEAD
              directories:
                - path: application-sets/example-apps/*
          - clusters: {}
          - list:
              elements:
                - values: 
                    suffix: '1'
                - values:
                    suffix: '2'
                - values: 
                    suffix: '3'
  template:
    metadata:
      name: '{{path.basename}}-{{name}}-{{values.suffix}}'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/codefresh-contrib/gitops-cert-level-2-examples.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated: 
          prune: true 
          selfHeal: true
