apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example05
  namespace: argocd
#  annotations:
#     argocd.argoproj.io/hook: SyncFail
spec:
  project: default
  source:
    repoURL: https://github.com/jonathanrboniface/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./sync-hooks-waves/05-sync-waves
  destination:
    server: https://kubernetes.default.svc
    namespace: example05
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
