apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example03
  namespace: argocd
  annotations:
     argocd.argoproj.io/hook: PostSync
spec:
  project: default
  source:
    repoURL: https://github.com/jonathanrboniface/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./sync-hooks-waves/03-postsync-cleanup
  destination:
    server: https://kubernetes.default.svc
    namespace: example03
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true 
      selfHeal: true 
      allowEmpty: false
