apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example01
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jonathanrboniface/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./sync-hooks-waves/01-default-order
  destination:
    server: https://kubernetes.default.svc
    namespace: example01
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true 
      selfHeal: true 
      allowEmpty: false
