apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example04
  namespace: argocd
  annotations:
     argocd.argoproj.io/hook: SyncFail
spec:
  project: default
  source:
    repoURL: https://github.com/jonathanrboniface/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./sync-hooks-waves/04-handle-sync-fail
  destination:
    server: https://kubernetes.default.svc
    namespace: example04
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
