apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example01
  namespace: argocd
  annotations:
     argocd.argoproj.io/hook: PreSync
spec:
  project: default
  source:
    repoURL: https://github.com/jonathanrboniface/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./sync-hooks-waves/02-presync-job
  destination:
    server: https://kubernetes.default.svc
    namespace: example02
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true 
      selfHeal: true 
      allowEmpty: false
