apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jonathanrboniface/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./environment-promotion/envs/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selHeal: true
